language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lukehungngo/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true run lukehungngo/react-test npm run test -- --coverage

after_success:
  # build image
  - docker build -t lukehungngo/complex-worker ./worker
  - docker build -t lukehungngo/complex-server ./server
  - docker build -t lukehungngo/complex-client ./client
  - docker build -t lukehungngo/complex-nginx ./nginx
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push image to docker hub
  - docker push lukehungngo/complex-worker
  - docker push lukehungngo/complex-server
  - docker push lukehungngo/complex-client
  - docker push lukehungngo/complex-nginx
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: complex
  env: Complex-env
  bucket_name: elasticbeanstalk-us-east-2-889622348088
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY