language: generic
sudo: required
services:
  - docker

before_install:
  - docker build - t lukehungngo/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true run lukehungngo/react-test npm run test -- --coverage

after_success:
  # build image
  - docker build -t lukehungngo/complex-worker ./worker
  - docker build -t lukehungngo/complex-server ./server
  - docker build -t lukehungngo/complex-client ./client
  - docker build -t lukehungngo/complex-nginx ./nginx
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push image to docker hub
  - docker push lukehungngo/complex-worker
  - docker push lukehungngo/complex-server
  - docker push lukehungngo/complex-client
  - docker push lukehungngo/complex-nginx
