version: '3'
services:
  postgres:
    image: "postgres"
  redis:
    image: "redis"
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: always
    ports:
      - "3000:80"    
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis #name of service
      - REDIS_PORT=6379
      - PGUSER=postgres #default user
      - PGHOST=postgres #name of service
      - PGDATABASE=postgres #default db
      - PGPASSWORD=postgres_password #default db
      - PGPORT=5432
    depends_on:
      - postgres
      - redis
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis